# Generated by Django 5.0.2 on 2024-02-11 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diseaseapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="person",
            new_name="dummy",
        ),
    ]
