# Generated by Django 5.0.2 on 2024-02-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseaseapp", "0003_rename_dummy_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("creator", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                ("experience", models.CharField(max_length=30)),
                ("hospital", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
        migrations.DeleteModel(
            name="person",
        ),
    ]
