# Generated by Django 5.0.2 on 2024-02-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseaseapp", "0005_review_alter_blogs_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
    ]
