# Generated by Django 5.0.2 on 2024-02-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseaseapp", "0006_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
