# Generated by Django 5.0.2 on 2024-02-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseaseapp", "0007_userregister"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="age",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
